export const REGION_OPTIONS = [
  "Plano Piloto",
  "Taguatinga",
  "Águas Claras",
  "Guará 1",
  "Guará 2",
  "Ceilândia",
  "Samambaia",
  "Sobradinho",
  "Sobradinho II",
  "Gama",
  "Santa Maria",
  "Riacho Fundo I",
  "Riacho Fundo II",
  "Cruzeiro",
  "Brazlândia",
  "Núcleo Bandeirante",
  "Recanto das Emas",
  "Lago Norte",
  "Lago Sul",
  "Paranoá",
  "Itapoã",
  "Varjão",
  "Vicente Pires",
  "Park Way",
  "Park Sul",
  "Candangolândia",
  "SIA",
  "SIG",
  "SCIA/Estrutural",
  "Fercal",
  "Sudoeste/Octogonal",
  "CAUB",
  "Noroeste",
  "Granja do Torto",
  "Arniqueiras",
  "Sol Nascente",
  "Jardim Botânico",
  "São Sebastião",
  "Planaltina",
  "Taquari",
] as const;

type RegionOptionTuple = typeof REGION_OPTIONS;
export type RegionOption = RegionOptionTuple[number];
